apiVersion: app.hasno.com/v1alpha1
kind: HALayerSet
metadata:
  name: halayerset-sample
  namespace: hasno-setup-operator-system
spec:
  deployments:
    - "nginx-test"
    - "nginx-prod"
  fenceAgentsSpec:
  - name: "fence_ipmilan_1"
    type: "fence_ipmilan"
    params:
      ip: "192.168.0.10"
      username: "admin"
      password: "password"
      ipport: "6241"
      lanplus: "1"
      pcmk_host_list: "sno1"
  - name: "fence_ipmilan_2"
    type: "fence_ipmilan"
    params:
      ip: "192.168.0.10"
      username: "admin"
      password: "password"
      ipport: "6252"
      lanplus: "1"
      pcmk_host_list: "sno2"
  nodesSpec:
    firstNodeName: "sno1"
    firstNodeIP: "192.168.126.241"
    secondNodeName: "sno2"
    secondNodeIP: "192.168.126.204"
